import React,{useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,ArrowRight,Menu,X,Plus,LayoutDashboard,Users,Kanban,CalendarCheck,ChartNoAxesCombined,Bell,Search,Check}from'lucide-react';
import'./styles.css';

const stages=[['NEW',24,'₹18.4L'],['QUALIFIED',14,'₹12.2L'],['CONSULTATION',8,'₹7.6L'],['PROPOSAL',6,'₹5.8L'],['BOOKED',4,'₹8.4L']];
const leads=[['Rahul & Priya','Proposal sent 2 days ago','₹3.5L','OVERDUE'],['Arjun & Meera','Consultation today, 4:30 PM','₹2.8L','TODAY'],['Kabir & Ananya','New enquiry from Instagram','₹4.2L','NEW']];
function Nav({open,setOpen,onDemo}){return <nav><a className="logo" href="#top">VYRAL<span>HQ</span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button><div className={'navlinks '+(open?'open':'')}><a href="#system">System</a><a href="#photographers">Photographers</a><a href="#why">About</a><button className="linkbtn" onClick={onDemo}>Login</button><a className="lime sm" href="#apply">Get VYRAL <ArrowUpRight size={16}/></a></div></nav>}
function Dashboard({close}){const[done,setDone]=useState([]);return <div className="demo"><aside><div className="logo">VYRAL<span>HQ</span></div>{[[LayoutDashboard,'Dashboard'],[Users,'Leads'],[Kanban,'Pipeline'],[CalendarCheck,'Follow-ups'],[ChartNoAxesCombined,'Marketing']].map(([I,t],i)=><button className={i===0?'active':''}><I size={18}/>{t}</button>)}</aside><main><header><div><small>SATURDAY, 22 AUGUST</small><h2>Good morning, Aanya.</h2></div><div className="head-actions"><Search/><Bell/><button className="lime sm"><Plus size={16}/> Add lead</button><button className="close" onClick={close}><X/></button></div></header><div className="answer">HOW IS YOUR BUSINESS DOING TODAY?</div><section className="metrics">{[['NEW LEADS','24','+18%'],['QUALIFIED','14','58%'],['CONSULTATIONS','08','This week'],['BOOKINGS','04','₹2.1L avg'],['REVENUE','₹8.4L','+24%']].map((m,i)=><div><small>{m[0]}</small><b className={i===4?'accent':''}>{m[1]}</b><span>{m[2]}</span></div>)}</section><section className="dash-grid"><div className="panel pipeline"><div className="paneltop"><h3>Pipeline</h3><span>₹52.4L open value</span></div>{stages.map((s,i)=><div className="stage"><span>{String(i+1).padStart(2,'0')}</span><b>{s[0]}</b><em>{s[1]} leads</em><strong>{s[2]}</strong><div style={{width:(100-i*12)+'%'}}/></div>)}</div><div className="panel actions"><div className="paneltop"><h3>Action center</h3><span>3 need attention</span></div>{leads.map((l,i)=><div className={'action '+(done.includes(i)?'done':'')}><div><b>{l[0]}</b><p>{l[1]}</p></div><strong>{l[2]}</strong><small>{done.includes(i)?'DONE':l[3]}</small><button onClick={()=>setDone([...done,i])}><Check size={15}/></button></div>)}</div></section></main></div>}
function App(){const[open,setOpen]=useState(false),[demo,setDemo]=useState(false);useEffect(()=>{document.body.style.overflow=demo?'hidden':''},[demo]);return <><div id="top" className="hero"><Nav open={open} setOpen={setOpen} onDemo={()=>setDemo(true)}/><div className="hero-copy"><p className="eyebrow">THE GROWTH OPERATING SYSTEM<br/>FOR PHOTOGRAPHERS</p><h1>WE MAKE<br/>PHOTOGRAPHERS<br/><i>HARD TO IGNORE.</i></h1><div className="hero-bottom"><p>Sales. Marketing. Growth.<br/>Built exclusively for photographers.</p><div><a className="lime" href="#apply">GET VYRAL <ArrowUpRight/></a><a className="ghost" href="#system">SEE THE SYSTEM <ArrowRight/></a></div></div></div><div className="scroll">SCROLL TO DISCOVER <span>↓</span></div></div>
<section className="problem"><div className="label">01 — THE PROBLEM</div><h2>YOU KNOW HOW TO SHOOT.<br/><span>BUT DOES YOUR BUSINESS<br/>KNOW HOW TO SELL?</span></h2><div className="chaos"><p>Your next booking is hiding somewhere between</p>{['INSTAGRAM','WHATSAPP','CALLS','SPREADSHEETS','NOTES','MEMORY'].map((x,i)=><span style={{'--i':i}}>{x}</span>)}</div></section>
<section id="system" className="journey"><div className="label">02 — THE SYSTEM</div><div className="journey-head"><h2>FROM ATTENTION<br/>TO REVENUE.</h2><p>One clear system for the entire journey. Every lead captured. Every conversation remembered. Every rupee connected back to where it started.</p></div><div className="steps">{['ATTENTION','LEAD','CONVERSATION','CONSULTATION','BOOKING','GROWTH'].map((x,i)=><div><small>0{i+1}</small><b>{x}</b><ArrowRight/></div>)}</div><button className="product" onClick={()=>setDemo(true)}><div><span>LIVE PRODUCT PREVIEW</span><h3>YOUR BUSINESS.<br/>AT A GLANCE.</h3><p>Know what needs attention, what’s converting and where your next booking is coming from.</p><em>OPEN INTERACTIVE DASHBOARD <ArrowUpRight/></em></div><div className="mini"><header><b>Good morning, Aanya.</b><Plus/></header><div className="mini-metrics"><b>24<small>NEW LEADS</small></b><b>14<small>QUALIFIED</small></b><b className="green">₹8.4L<small>REVENUE</small></b></div>{stages.slice(0,4).map(s=><p><span>{s[0]}</span><i>{s[1]}</i><b>{s[2]}</b></p>)}</div></button></section>
<section className="philosophy"><p>YOU DON'T NEED<br/>MORE FOLLOWERS.</p><h2>YOU NEED MORE<br/><i>RIGHT CLIENTS.</i><br/>AND A SYSTEM<br/>TO CLOSE THEM.</h2></section>
<section id="photographers" className="photographers"><div className="label">03 — BUILT FOR PHOTOGRAPHERS</div><div className="profiles"><div className="portrait one"><div><span>WEDDINGS / NEW DELHI</span><h3>THE HOUSE<br/>ON THE CLOUDS</h3></div></div><div className="profile-copy"><h2>THEY'RE<br/>ALREADY <i>VYRAL.</i></h2><p>For the photographer building a name. For the studio ready to scale. For the team that refuses to lose another great enquiry in a sea of DMs.</p><div><button>WEDDING STUDIOS</button><button>PORTRAIT ARTISTS</button><button>CREATIVE TEAMS</button></div></div></div></section>
<section id="why" className="why"><div className="label">04 — WHY WE EXIST</div><h2>MARKETING GETS<br/>YOU NOTICED.<br/><i>VYRAL GETS<br/>YOU BOOKED.</i></h2><div className="tri"><span>MARKETING</span><ArrowRight/><span>SALES</span><ArrowRight/><span>REVENUE</span></div></section>
<section id="apply" className="final"><span>YOUR NEXT CHAPTER STARTS HERE.</span><h2>READY TO<br/>GO <i>VYRAL?</i></h2><a className="lime big" href="mailto:hello@vyralhq.com">BUILD MY GROWTH SYSTEM <ArrowUpRight/></a><p>Limited onboarding for photography studios.</p></section><footer><div className="logo">VYRAL<span>HQ</span></div><p>YOU SHOOT.<br/>WE BUILD THE MACHINE.</p><div><a href="#system">SYSTEM</a><a href="#why">ABOUT</a><a href="#apply">CONTACT</a><a href="#top">INSTAGRAM</a></div><small>© 2026 VYRAL HQ</small></footer>{demo&&<Dashboard close={()=>setDemo(false)}/>}</>}
createRoot(document.getElementById('root')).render(<App/>);
